### ISSUE TITLE
Can't import without confluent dependencies

### ISSUE THREAD

**Issue by simplesteph** [manub/scalatest-embedded-kafka#133]
@francescopellegrini  I understand you need the schema registry in this library but that's not "pure kafka" and the dependencies actually rely on importing the Confluent Schema Registry. Any import of the newly `  "net.manub" %% "scalatest-embedded-kafka" % "1.1.0-kafka1.1" % "test",` will result in that error:

```
Error:Error while importing SBT project:<br/>...<br/><pre>[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: io.confluent#kafka-avro-serializer;4.1.0: not found
[error] unresolved dependency: io.confluent#kafka-schema-registry;4.1.0: not found
[error] (*:ssExtractDependencies) sbt.librarymanagement.ResolveException: unresolved dependency: io.confluent#kafka-avro-serializer;4.1.0: not found
[error] unresolved dependency: io.confluent#kafka-schema-registry;4.1.0: not found
[error] Total time: 80 s, completed 05/05/2018 10:50:25 AM</pre><br/>See complete log in <a href="file:/Users/stephanemaarek/Library/Logs/IdeaIC2017.2/sbt.last.log">file:/Users/stephanemaarek/Library/Logs/IdeaIC2017.2/sbt.last.log</a>
```

Please extract the schema registry dependency into a separate dependency / project. This will make more sense, and will probably need to document to import the confluent repos in the resolvers

**Comment by manub** [comment]
I have been outside the Kafka world for a bit, and I didn't realise that. A separate version will be released - however I have very little time for contributing. If you or @francescopellegrini could issue a PR that'd be great and I'll release it ASAP, otherwise it may take me a little bit to make the change.

**Comment by francescopellegrini** [comment]
This was my initial plan, if you read back to #115, but there was (nor yet is) any hook to use to trigger additional logic in `withRunningKafka` or similar methods.
`EmbeddedSR` could be moved away by making `EmbeddedServer` not `sealed`, but I couldn't figure out a way to add the Schema Registry conf properties to `EmbeddedKafkaConfig` while leaving it separate in its own project.
I'll try to find another solution, but I'm afraid it's not going to be quick.. as per the missing resolver, that was my bad not to update the docs.

**Comment by simplesteph** [comment]
@francescopellegrini  I understand.
Maybe you can have 
`scalatest-embedded-kafka-confluent` addon / project / module which provides a `withRunningKafkaConfluent` which wraps `withRunningKafka` and adds a schema registry in the mix

**Comment by simplesteph** [comment]
@manub if you do a pre-release on maven central I can test that with my project: https://github.com/simplesteph/kafka-security-manager 
I don't have enough background at how the project works to look at the PR, but I can tell you if it's all good from a user perspective once you have a pre-release

Thanks for the quick turnaround!

**Comment by francescopellegrini** [comment]
@manub I was working on a PR myself (which goes in a very different direction) but I'll review yours soon.

**Comment by manub** [comment]
@simplesteph I'd rather not publish another version for now and I've looked into deploying snapshots to bintray but I had very little success!

Can I suggest you try to build the code yourself? It should be pretty straightforward

- clone the project and checkout the `split-schema-registry` branch
- run `sbt +publishLocal` to publish locally all the three projects, cross built for 2.11 and 2.12
- change your project to use the local version, which would be `1.1.0-nosr-SNAPSHOT`

There's no special requirements to build it.

Please let me know if this helps.

**Comment by simplesteph** [comment]
@manub I gave it a try but didn't work
```
info] 	published ivy to /Users/stephanemaarek/.ivy2/local/net.manub/scalatest-embedded-schema-registry_2.11/1.1.0-nosr-SNAPSHOT/ivys/ivy.xml
[error] java.lang.IllegalStateException: Ivy file not found in cache for net.manub#scalatest-embedded-kafka-root_2.11;1.1.0-nosr-SNAPSHOT!
[error] 	at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
[error] 	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
[error] 	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$deliver$2(IvyActions.scala:100)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.deliver(IvyActions.scala:95)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2242)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2241)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (publishLocal) java.lang.IllegalStateException: Ivy file not found in cache for net.manub#scalatest-embedded-kafka-root_2.11;1.1.0-nosr-SNAPSHOT!
```

**Comment by manub** [comment]
@simplesteph I'm publishing a version to bintray only now.

Please add `Resolver.bintrayRepo("manub", "maven")` to your resolvers in sbt (https://www.scala-sbt.org/1.x/docs/Resolvers.html) and then specify version `1.1.0-kafka1.1-nosr`. Let me know, in case I'll publish to Maven Central.

**Comment by simplesteph** [comment]
@manub  it works, and tests are passing! No need for confluent repo anymore
Cheers!
